@hostname = localhost
@port = 3030
@host = {{hostname}}:{{port}}

### GET ALL Pokemons
GET http://{{host}}/pokemons
Accept: application/json

### GET Pokemon by ID
GET http://{{host}}/pokemons/1
Accept: application/json

### POST New Pokemon
POST http://{{host}}/pokemons
Content-Type: application/json
Accept: application/json

{
  "pokemonId": "new_pokemon_id",
  "pokemonName": "Pikachu",
  "imageUrl": "https://example.com/pikachu.png"
}

### PUT Update Pokemon
PUT http://{{host}}/pokemons/1
Content-Type: application/json
Accept: application/json

{
  "pokemonId": "new_pokemon_id", 
  "pokemonName": "Charizard",
  "imageUrl": "https://example.com/charizard.png"
}

### DELETE Pokemon
DELETE http://{{host}}/pokemons/3
Accept: application/json


### Guardar Pokemon de la PokeApi
@pokemonID = 12
POST http://{{host}}/pokemons/import-pokemon/{{pokemonID}}
Accept: application/json


### Importar Rango de Pokemons de la PokeApi
@startId = 1
@endId = 151
GET http://{{host}}/pokemons/import-range?startId={{startId}}&endId={{endId}}
Accept: application/json