@hostname = localhost
@port = 3030
@host = {{hostname}}:{{port}}

### GET ALL PokemonTypes
GET http://{{host}}/pokemon-type
Accept: application/json

### GET PokemonType by ID
GET http://{{host}}/pokemon-type/1
Accept: application/json

### POST New PokemonType
POST http://{{host}}/pokemon-type
Content-Type: application/json
Accept: application/json

{
  "pokemon": {
    "pokemonId": "1"  
  },
  "typeElement": {
    "typeElementId": 1   
  }
}

### PUT Update PokemonType
PUT http://{{host}}/pokemon-type/15
Content-Type: application/json
Accept: application/json

{
  "pokemon": {
    "pokemonId": "2"  
  },
  "typeElement": {
    "typeElementId": 2  
  }
}

### DELETE PokemonType
DELETE http://{{host}}/pokemon-type/3
Accept: application/json
