@hostname = localhost
@port = 3030
@host = {{hostname}}:{{port}}

### GET ALL Teams
GET http://{{host}}/teams
Accept: application/json

### GET Team by ID
GET http://{{host}}/teams/1
Accept: application/json

### POST New Team
POST http://{{host}}/teams
Content-Type: application/json
Accept: application/json

{
  "teamName": "Team Rocket",
  "user": {
    "userId": "user1"  
  }
}

### PUT Update Team
PUT http://{{host}}/teams/2
Content-Type: application/json
Accept: application/json

{
  "teamName": "Team Pikachu",
  "user": {
    "userId": "user2" 
  }
}

### DELETE Team
DELETE http://{{host}}/teams/3
Accept: application/json


### POST New Team with Pokemons
POST http://{{host}}/teams/create-with-pokemons
Content-Type: application/json
Accept: application/json

{
  "teamName": "Team LosPikachus",
  "userId": "user1",  
  "pokemonIds": ["1", "2", "3", "4", "5", "6"] 
}